commit message:
prior to this commit, this contract should compile but would throw:

```
@external
def foo():
    for i in [[], []]:
        pass
```

```
TypeError: _BytestringT.compare_type() missing 1 required positional argument: 'other'
```

the issue is that the possible types produced by `types_from_List` for
an empty list include type class objects (e.g. `BytesT`, `StringT`).
this would cause `get_common_types` to throw the above error in
downstream code when calling `compare_type()`. this commit fixes the
issue by providing the correct generic type acceptors instead of
uninstantiated class objects.