fix: indexing into literal list (#3378)
a regression was introduced in 046ea166d whereby the following contract
used to compile but now panics:
```
@external
def foo():
    f: uint256 = 1
    a:bool = 1 == [1,2,4][f] + -1
```
```
AssertionError: unreachable, uint256 != int8
```

the issue was that, previously, different integer types in vyper were
represented by different types in python. however, now all integer types
inherit from `IntegerT`. this commit fixes the issue by using the
correct (and hygienically appropriate) `type.compare_type(other)`,
instead of checking python-level type equality.

the lark grammar also needed to be changed to enable accessing a literal
list directly.

---------

Co-authored-by: Charles Cooper <cooper.charles.m@gmail.com>